#!/bin/bash
sudo apt-get install libboost-program-options-dev
sudo pip install tweepy
#pcl dependencies
sudo apt-get install libpcl-1.7-all-dev
#images
sudo apt-get install imagemagick

#libfreenect2 dependencies
sudo apt-get install build-essential libturbojpeg libjpeg-turbo8-dev libtool autoconf libudev-dev cmake mesa-common-dev freeglut3-dev libxrandr-dev doxygen libxi-dev automake
apt-get install opencl-headers

UBUNTU_TRUSTY=`echo ${UBUNTU_VERSION}"==14.04" | bc`
if [[ $UBUNTU_TRUSTY -eq 1 ]];
then
  sudo dpkg -i libglfw3*_3.0.4-1_*.deb
fi

pushd src/libraries/libfreenect2 && mkdir -p build && cd build && cmake .. && \
    sudo make install  || \
    { echo 'Error: libfreenect2 failed' >&2; exit 1; }
popd
pushd src/libraries/libfreenect2/depends/ sh install_ubuntu.sh
popd
